In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


In [4]:
import numpy as np 
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[2])

30


In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
arr[1] = 100
print(arr)

[ 10 100  30  40  50]


In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.max(arr))

50


In [11]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr.argmax())

4


In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.min(arr))

10


In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.argmin(arr))

0


In [14]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.cumsum(arr))

[ 10  30  60 100 150]


In [15]:
import numpy as np

arr = np.array([2,3,4])
print(np.cumprod(arr))

[ 2  6 24]
