In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.delete(arr,2))

[10 20 40 50]


In [2]:
import numpy as np

a = np.array([10,20,30])

b = np.array([40,50,60])

print(np.concatenate((a,b)))

[10 20 30 40 50 60]


In [4]:
import numpy as np

arr = np.array([50,10,40,20,30])

print(np.sort(arr))

[10 20 30 40 50]


In [6]:
import numpy as np

arr = np.array([10,0,20,0,30,40])

print(np.nonzero(arr))

(array([0, 2, 4, 5]),)


In [12]:
import numpy as np

arr = np.array([10,20,30,40,50])

new_arr = np.insert(arr,3,35)

print(new_arr)

[10 20 30 35 40 50]


In [14]:
import numpy as np

arr = np.array([10, 20, 20, 30, 10, 40, 30])

print(np.unique(arr))

[10 20 30 40]


In [16]:
import numpy as np

arr = np.array([10,0,20,0,30,40,0])

print(np.count_nonzero(arr))

4


In [17]:
import numpy as np

arr = np.array([10,20,30])

print(np.repeat(arr,3))

[10 10 10 20 20 20 30 30 30]


In [20]:
import numpy as np

arr = np.array([85,90,75,88,92])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))

430
86.0
88.0
92
75


In [26]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

1
(4,)
4
int64
8
32


In [36]:
import numpy as np

a = np.array([10,20,30])

b = np.array([40,50,60])

print(np.stack((a,b)))

[[10 20 30]
 [40 50 60]]


In [38]:
import numpy as np

arr = np.array([10, 20, 30, 40])
new_arr = arr.copy()
print(arr)
print(new_arr)

[10 20 30 40]
[10 20 30 40]


In [2]:
import numpy as np

arr = np.array([10,20,30,40])
new_arr = arr.view()
new_arr[2] = 80
print(arr)
print(new_arr)

[10 20 80 40]
[10 20 80 40]


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np

arr = np.array([10,20,30,40])
new_arr = arr.astype(float)
print(new_arr)
print(new_arr.dtype)

[10. 20. 30. 40.]
float64


In [16]:
import numpy as np

arr = np.array([10,20,30])
print(np.repeat(arr,2))
print(np.tile(arr,2))

[10 10 20 20 30 30]
[10 20 30 10 20 30]


In [24]:
import numpy as np

arr = np.array([75,82,90,68,95,88,72,91])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.median(arr))

if np.mean(arr) >= 75:
    print("Average marks are greater than or equal to 75")
else:
    print("Average marks are less than 75")

661
82.625
95
68
85.0
Average marks are greater than or equal to 75


In [25]:
import numpy as np

arr = np.array([50,20,80,10,60,30])

print(np.sort(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.unique(arr))

sorted_arr = np.sort(arr)
position = np.searchsorted(sorted_arr, 45)

print(position)

[10 20 30 50 60 80]
80
10
41.666666666666664
[10 20 30 50 60 80]
3


In [7]:
#

[10, 20, 30, 40, 50]
10
20
30
40
50


In [9]:
#

661
66.1
92
32
[32 40 45 55 65 76 78 88 90 92]
70.5
[32 40 45 55 65 76 78 88 90 92]
10
Insertion Position of 70: 5
Good Performance


In [31]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

copy_arr = arr.copy()
view_arr = arr.view()

copy_arr[1] = 200
view_arr[3] = 400

print("Original Array:", arr)
print(copy_arr)
print(view_arr)

Original Array: [ 10  20  30 400  50]
[ 10 200  30  40  50]
[ 10  20  30 400  50]


In [29]:
import numpy as np

arr = np.array([40, 10, 20, 10, 30, 0, 50, 20])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))

print(np.sort(arr))
print(np.unique(arr))

print(np.nonzero(arr))
print(np.count_nonzero(arr))

my_list = arr.tolist()
print("Python List:", my_list)

1
(8,)
8
int64
8
64
180
22.5
20.0
50
0
[ 0 10 10 20 20 30 40 50]
[ 0 10 20 30 40 50]
(array([0, 1, 2, 3, 4, 6, 7]),)
7
Python List: [40, 10, 20, 10, 30, 0, 50, 20]


In [30]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])


print(arr.reshape(2, 3))

# 2. Convert into 1D
arr = arr.flatten()
print("Flattened Array:", arr)

# 3. Create copy
arr = arr.copy()

# 4. Insert 25 at index 2
arr = np.insert(arr, 2, 25)
print("After Insert:", arr)

# 5. Append 70
arr = np.append(arr, 70)
print("After Append:", arr)

# 6. Delete element at index 0
arr = np.delete(arr, 0)
print("After Delete:", arr)

# 7. Sort final array
arr = np.sort(arr)
print("Final Sorted Array:", arr)

# 8. Final array properties
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

[[10 20 30]
 [40 50 60]]
Flattened Array: [10 20 30 40 50 60]
After Insert: [10 20 25 30 40 50 60]
After Append: [10 20 25 30 40 50 60 70]
After Delete: [20 25 30 40 50 60 70]
Final Sorted Array: [20 25 30 40 50 60 70]
Dimensions: 1
Shape: (7,)
Size: 7
Data Type: int64


In [31]:
import numpy as np

numbers = []

for i in range(5):
    num = int(input("Enter number: "))
    numbers.append(num)

arr = np.array(numbers)

print("Original Array:", arr)

sorted_arr = np.sort(arr)

print(sorted_arr)
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.unique(arr))
print(np.count_nonzero(arr))

additional = int(input("Enter additional number: "))

position = np.searchsorted(sorted_arr, additional)

print("Insertion Position:", position)

Enter number:  3
Enter number:  5
Enter number:  4
Enter number:  6
Enter number:  7


Original Array: [3 5 4 6 7]
[3 4 5 6 7]
7
3
25
5.0
5.0
[3 4 5 6 7]
5


Enter additional number:  3


Insertion Position: 0


In [8]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr.tolist())

for i in arr:
    print(i)

[10, 20, 30, 40, 50]
10
20
30
40
50


In [26]:
import numpy as np

arr = np.array([45,78,90,32,65,88,55,92,40,76])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sort(arr))
print(np.median(arr))
print(np.unique(arr))
print(np.count_nonzero(arr))

sorted_arr = np.sort(arr)
print(np.searchsorted(sorted_arr,70))

if np.mean(arr) >= 60:
    print("good performance")
else:
    print("needs improvement")

661
66.1
92
32
[32 40 45 55 65 76 78 88 90 92]
70.5
[32 40 45 55 65 76 78 88 90 92]
10
5
good performance


In [30]:
import numpy as np

arr = np.array([10,20,30,40,50])
new_arr = arr.copy()
print(arr)
print(new_arr)
new_arr = arr.view()
new_arr[2] = 100
print(arr)
print(new_arr)

[10 20 30 40 50]
[10 20 30 40 50]
[ 10  20 100  40  50]
[ 10  20 100  40  50]
