In [3]:
import numpy as np

salaries = np.array([25000, 32000, 28000, 45000, 38000, 52000, 41000, 60000, 35000, 48000])

print(salaries[1])
print(salaries[3])
print(salaries[5])
print(salaries[9])

32000
45000
52000
48000


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[0],arr[1],arr[2],arr[3],arr[4],arr[5],arr[6],arr[7])
print(arr[-1],arr[-2],arr[-3],arr[-4],arr[-5],arr[-6],arr[-7],arr[-8])

10 20 30 40 50 60 70 80
80 70 60 50 40 30 20 10


In [12]:
import numpy as np

arr = np.array([15, 25, 35, 45, 55, 65, 75, 85])
arr[[2,6]] = [200,400]
print(arr)

[ 15  25 200  45  55  65 400  85]


In [20]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0] + arr[2])
print(arr[3] - arr[1])
print(arr[0] * arr[1])
print(arr[2] / arr[4])
print(arr[0] ** arr[1])

40
20
200
0.6
7766279631452241920


In [37]:
import numpy as no

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(arr[0])
print(arr[2])
print(arr[:,0])
print(arr[:,3])

[10 20 30 40]
[ 90 100 110 120]
[10 50 90]
[ 40  80 120]


In [40]:
import numpy as np

arr = np.array([
 [[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18]]
])
print(arr[0][1][2])
print(arr[1][1][1])
print(arr[2][0][0])

6
11
13


In [41]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
updated_arr = arr + 5
print(updated_arr)

[15 25 35 45 55]


In [44]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
arr1 = np.array([2, 4, 5, 8, 10])
print(arr + arr1)
print(arr - arr1)
print(arr * arr1)
print(arr / arr1)

[12 24 35 48 60]
[ 8 16 25 32 40]
[ 20  80 150 320 500]
[5. 5. 6. 5. 5.]


In [2]:
import numpy as np

arr = np.array([45, 12, 89, 34, 67, 23, 91, 56, 8, 72])
print(np.max(arr))
print(np.min(arr))
print(np.argmax(arr))
print(np.argmin(arr))

91
8
6
8


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print(np.std(arr))
print(np.var(arr))

17.07825127659933
291.6666666666667


In [8]:
import numpy as np

arr = np.array([2, 3, 4, 5])
print(arr.cumsum())
print(arr.cumprod())

[ 2  5  9 14]
[  2   6  24 120]


In [12]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[0][0] = 100
arr[0][2] = 200
arr[1][1] = 500
print(arr)

[[100  20 200]
 [ 40 500  60]
 [ 70  80  90]]


In [15]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr1 = np.array([1, 2, 3])
print(arr + arr1)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [ ]:
import numpy as no


arr = np.array([