In [3]:
import numpy as np 

arr = np.array([80,90,70])
print(arr)

[80 90 70]


In [4]:
import numpy as np 

arr = np.array([[80,90,70],
                [75,85,75],
                [90,95,88]
])
print(arr)

[[80 90 70]
 [75 85 75]
 [90 95 88]]


In [9]:
import numpy as np

v = np.array([10,20,30])
print(v)
print(np.ndim(v))
print(np.shape(v))

[10 20 30]
1
(3,)


In [10]:
import numpy as np

v = np.array([10, 20, 30])

print(v[0])
print(v[1])
print(v[2])


10
20
30


In [12]:
import numpy as np

arr = np.array([
    [1,2],
    [4,5]
])
print(arr)
print(np.ndim(arr))
print(np.shape(arr))

[[1 2]
 [4 5]]
2
(2, 2)


In [13]:
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])
print(A[0,0])
print(A[0,1])
print(A[1,2])


1
2
6


In [14]:
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])
print(A.shape)

(2, 3)


In [13]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
print(C)
print(np.shape(A))
print(np.shape(B))

[[ 6  8]
 [10 12]]
(2, 2)
(2, 2)


In [15]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print(C)

[[19 22]
 [43 50]]


In [16]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A*B
print(C)

[[ 5 12]
 [21 32]]


In [20]:
import numpy as np

A = np.array([[2,1,3],[4,0,2]])
B = np.array([[5,2],[1,4],[3,7]])

C = np.dot(A,B)
print(C)

[[20 29]
 [26 22]]


In [22]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print(np.transpose(A))

[[1 4]
 [2 5]
 [3 6]]


In [26]:
import numpy as np 
A = np.array([ 
[1, 2], 
[3, 4] 
]) 
det = np.linalg.det(A) 
print(det) 

-2.0000000000000004


In [1]:
import numpy as np

arr = np.array([
    [1,2],
    [3,4]
])
det = np.linalg.det(arr)
print(det)

-2.0000000000000004


In [2]:
import numpy as np

arr = np.array([
    [1,2],
    [3,4]
])
arr_inv = np.linalg.inv(arr)
print(arr_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
import numpy as np 
A = np.array([[1, 2],[3, 4]]) 
A_inv = np.linalg.inv(A) 
result = A @ A_inv 
print(np.allclose(result, np.eye(2)))

True


In [4]:
import numpy as np

A = np.array([[1, 2],
              [2, 4]])

print(np.linalg.det(A))

0.0
