In [1]:
import numpy as np

A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [2]:
import numpy as np

A = np.array([
    [10, 20],
    [30, 40]
])
B = np.array([
    [2, 5],
    [10, 15]
])
C = A - B 
print(C)

[[ 8 15]
 [20 25]]


In [12]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [4]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.transpose(A))


[[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.det(A))

-2.0000000000000004


In [6]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
import numpy as np

A = np.array([
    [2, 0],
    [0, 3]
])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)

[2.+0.j 3.+0.j]


In [16]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 1]
])
print(np.linalg.matrix_rank(A))

2


In [17]:
import numpy as np

A = np.array([
    [2,1],
    [1,3]
])
B = np.array([5,6])
print(np.linalg.solve(A,B))

[1.8 1.4]


In [18]:
import numpy as np

A = np.array([
    [1,1,1],
    [2,1,1],
    [1,2,1]
])
B = np.array([6,7,8])
print(np.linalg.solve(A,B))

[1. 2. 3.]


In [19]:
import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])
print(np.dot(A,B))

32


In [20]:
import numpy as np

A = np.array([
    [3, 4],
    [0, 5]
])
print(np.linalg.norm(A))

7.0710678118654755


In [21]:
import numpy as np

A = np.array([
    [5, 2, 1],
    [0, 4, 3],
    [0, 0, 6]
])
print(np.trace(A))

15


In [22]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [0, 4, 5],
    [1, 0, 6]
])
print(np.linalg.det(A))

22.000000000000004


In [23]:
import numpy as np

A = np.array([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 4]
])
print(np.linalg.inv(A))

[[1.   0.   0.  ]
 [0.   0.5  0.  ]
 [0.   0.   0.25]]
