In [4]:
import numpy as np

A = np.array([
    [1,1],
    [2,3]
])
B = np.array([7,17])
print(np.linalg.solve(A,B))

[4. 3.]


In [7]:
import numpy as np

A = np.array([
    [1,1,1],
    [2,1,1],
    [1,2,1]
])
B = np.array([6,7,8])
print(np.linalg.solve(A,B))

[1. 2. 3.]


In [12]:
import numpy as np

A = np.array([
    [4,0],
    [0,5]
])
egenvalues,egenvectors = np.linalg.eig(A)
print(egenvalues)
print(egenvectors)

[4.+0.j 5.+0.j]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [13]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
])
print(np.linalg.matrix_rank(A))

1


In [21]:
import numpy as np

A = np.array([
    [2, 1],
    [4, 2]
])
det = np.linalg.det(A)
print(det)
if det == 0:
    print("No inverse")
else:
    print(np.linalg.inv(A))

0.0
No inverse


In [22]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

C = A @ B
print(C)


[[ 58  64]
 [139 154]]


In [26]:
import numpy as np

A = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])
print(A.T)

[[10 30 50]
 [20 40 60]]


In [1]:
import numpy as np

A = np.array([
    [4, 7],
    [2, 6]
])
print(np.linalg.inv(A))

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [4]:
import numpy as np

A = np.array([
    [1,1,1],
    [2,1,1],
    [1,2,1]
])
B = np.array([6,8,9])
print(np.linalg.solve(A,B))

[2. 3. 1.]


In [6]:
import numpy as np

A = np.array([
    [1,1,1],
    [2,1,1],
    [1,2,1]
])
B = np.array([6,28,9])
print(np.linalg.solve(A,B))

[ 22.   3. -19.]


In [7]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.linalg.matrix_rank(A))

2


In [11]:
import numpy as np

A = np.array([
    [5, 0],
    [0, 2]
])
egenvalues, eigenvectors = np.linalg.eig(A)
print(egenvalues)

[5.+0.j 2.+0.j]


In [12]:
import numpy as np 

A = np.array([
    [3, 4],
    [0, 0]
])
print(np.linalg.norm(A))

5.0


In [15]:
import numpy as np

A = np.array([
    [2, 4, 5],
    [0, 6, 7],
    [0, 0, 8]
])
print(np.trace(A))

16
