In [4]:
import numpy as np

marks = np.array([78, 65, 89, 92, 56, 74, 88])
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))

77.42857142857143
92
56
12.442520907380958


In [12]:
import numpy as np

salaries = np.array([25000, 32000, 28000, 45000, 38000, 52000])
print(np.mean(salaries))
print(np.max(salaries))
print(np.min(salaries))
print(salaries[salaries > 40000])

36666.666666666664
52000
25000
[45000 52000]


In [16]:
import numpy as np

temp = np.array([28, 30, 27, 32, 35, 31, 29])
print(np.mean(temp))
print(np.max(temp))
print(np.min(temp))
print(temp[temp > 30])

30.285714285714285
35
27
[32 35 31]


In [19]:
import numpy as np

data = np.array([1200, 1500, 1100, 1800, 2000, 1700])
print(np.mean(data))
print(np.sum(data))

1550.0
9300


In [29]:
import numpy as np

arr = np.array([45, 67, 23, 89, 56, 92, 34, 78, 61, 50])
print(arr.shape)
print(arr.size)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.sort(arr))
print(arr[arr > 50])
print(arr[::-1])

(10,)
10
92
23
59.5
21.5
[23 34 45 50 56 61 67 78 89 92]
[67 89 56 92 78 61]
[50 61 78 34 92 56 89 23 67 45]


In [36]:
import numpy as np

marks = np.array([65, 78, 92, 56, 88, 73, 45, 90])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(marks[marks > 75])

587
73.375
92
45
[78 92 88 90]


In [40]:
import numpy as np

salary = np.array([22000, 35000, 28000, 45000, 52000, 31000, 40000])
print(np.mean(salary))
print(np.max(salary))
print(np.min(salary))
print(salary[salary > 30000])
print(salary[salary < 30000])


36142.857142857145
52000
22000
[35000 45000 52000 31000 40000]
[22000 28000]


In [43]:
import numpy as np

prices = np.array([499, 799, 299, 999, 599, 1299, 399])
print(np.sum(prices))
print(np.mean(prices))
print(np.max(prices))
print(np.min(prices))
print(prices[prices > 500])

4893
699.0
1299
299
[ 799  999  599 1299]


In [46]:
import numpy as np

temp = np.array([28, 32, 35, 27, 30, 36, 31])
print(np.mean(temp))
print(np.max(temp))
print(np.min(temp))
print(temp[temp > 30])
print(np.sum(temp > 30))

31.285714285714285
36
27
[32 35 36 31]
4


In [48]:
import numpy as np

sales = np.array([1200, 1500, 900, 2000, 1750, 2200, 1300])
print(np.sum(sales))
print(np.mean(sales))
print(np.max(sales))
print(np.min(sales))
print(sales[sales > 1500])

10850
1550.0
2200
900
[2000 1750 2200]


In [58]:
import numpy as np

numbers = np.array([10, 25, 40, 15, 60, 35, 80, 5])
print(numbers[numbers > 30])
print(numbers[numbers < 20])
print(numbers[numbers %2 == 0])
print(numbers[numbers %2 != 0])

[40 60 35 80]
[10 15  5]
[10 40 60 80]
[25 15 35  5]


In [59]:
import numpy as np

marks = np.array([35, 78, 42, 29, 65, 18, 90, 55])

passing = marks[marks >= 40]
failed = marks[marks < 40]

print("Passing marks:", passing)
print("Failed marks:", failed)
print("Number of passed students:", len(passing))
print("Number of failed students:", len(failed))


Passing marks: [78 42 65 90 55]
Failed marks: [35 29 18]
Number of passed students: 5
Number of failed students: 3


In [66]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50, 60])
print(np.where(numbers==30))
print(np.where(numbers==50))

(array([2]),)
(array([4]),)


In [72]:
import numpy as np

marks = np.array([78, 45, 92, 56, 88, 34, 67])
print(np.sort(marks))
print(np.sort(marks)[::-1])
print(np.sort(marks)[-3:][::-1])

[34 45 56 67 78 88 92]
[92 88 78 67 56 45 34]
[92 88 78]
