In [2]:
import numpy as np

marks = np.array([85,90,75,88,92])

print(np.std(marks))

5.966573556070519


In [6]:
import numpy as np

A = np.array([50,50,50,50,50])
B = np.array([10,30,50,70,90])

print(np.mean(A))
print(np.mean(B))

print(np.std(A))
print(np.std(B))

50.0
50.0
0.0
28.284271247461902


In [9]:
import numpy as np

arr = np.array([1,3,5,7,9])

print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

5.0
2.8284271247461903
8.0


In [10]:
import numpy as np

marks = np.array([85,90,75,88,92])

print(np.var(marks))

35.6


In [20]:
import numpy as np

marks = np.array([85,90, 75, 88, 92])

print(np.argmax(marks))

4


In [21]:
import numpy as np

marks = np.array([85,90, 75, 88, 92])

print(np.argmin(marks))

2


In [3]:
import numpy as np

marks = np.array([10,20,30,40])

print(np.cumsum(marks))

[ 10  30  60 100]


In [5]:
import numpy as np

marks = np.array([85,90, 75, 88, 92])

print(np.cumsum(marks))

[ 85 175 250 338 430]


In [4]:
import numpy as np

arr = np.array([1,3,5,7,9])

print(np.cumprod(arr))

[  1   3  15 105 945]


In [9]:
import numpy as np

arr = np.array([2,3,4,5])

print(np.cumprod(arr))

[  2   6  24 120]


In [10]:
import numpy as np 
salary = np.array([25000,30000,35000,40000])

print(salary[2])

35000


In [13]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


In [14]:
arr = np.array([10,20,30,40,50])

print(arr[-1])
print(arr[-2])
print(arr[-5])

50
40
10


In [15]:
arr = np.array([100,200,300,400])

print(arr[0])
print(arr[1])

100
200


In [17]:
salary = np.array([25000,30000,35000,40000])

print(salary)

[25000 30000 35000 40000]


In [3]:
import numpy as np 
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
]) 
print(arr[1, 0, 1])

8


In [5]:
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[1])

10
20


In [4]:

arr = np.array([10,20,30,40])
print(arr[0],arr[2])

10 30


In [2]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr[2] + arr[3])

70


In [3]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr[0] * arr[2])

300


In [4]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr[1] / arr[0])

2.0


In [8]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr[3] - arr[1])

20


In [10]:
import numpy as np
arr = np.array([2,3,4])
print(arr[1] ** arr[0])

9


In [11]:
import numpy as np
arr = np.array([15,20,35])
print(arr[2] % arr[0])

5


In [12]:
import numpy as np

arr = np.array([10,20,30,40])
arr[2]=100
print(arr)

[ 10  20 100  40]


In [13]:
import numpy as np

arr = np.array([10,20,30,40])
arr[0]=50
print(arr)

[50 20 30 40]


In [15]:
import numpy as np

arr = np.array([10,20,30,40])

arr[[1,3]] = [200,400]
print(arr)

[ 10 200  30 400]


In [19]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


In [20]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,2])
print(arr[1,0])
print(arr[2,1])

30
40
80


In [21]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,0])

10


In [22]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


In [24]:
import numpy as np
arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr[0,1,2])

6


In [25]:
import numpy as np 
class UpdateArray: 
   def updateNpArray(): 
       arr = np.array([10,20,30,40,50]) 
       updatedArray = arr + 5 
       print(updatedArray) 
obj = UpdateArray 
obj.updateNpArray()

[15 25 35 45 55]


In [26]:
import numpy as np

arr = np.array([10,20,30,40,50])
updated_array = arr + 5
print(updated_array)

[15 25 35 45 55]


In [27]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr1 = np.array([5,15,20,25,30])
print(arr + arr1)

[15 35 50 65 80]


In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr1 = np.array([5,15,20,25,30])
print(arr - arr1)

[ 5  5 10 15 20]


In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr1 = np.array([5,15,20,25,30])
print(arr * arr1)

[  50  300  600 1000 1500]


In [3]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr1 = np.array([5,15,20,25,30])
print(arr / arr1)

[2.         1.33333333 1.5        1.6        1.66666667]


In [4]:
import numpy as np

arr = np.array([10,20,30,40,50])
condition = arr > 35
print(condition)

[False False False  True  True]


In [5]:
import numpy as np

marks = np.array([25, 45, 60, 30, 80])

passed = marks >= 40

print(passed)

[False  True  True False  True]


In [9]:
import numpy as np

arr= np.array([10,20,30])
print(arr + 5)

[15 25 35]


In [13]:
import numpy as np

a = np.array([10,20,30])
b = np.array([1])
print(a+b)
print(a.shape)
print(b.shape)

[11 21 31]
(3,)
(1,)


In [16]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40, 50],
    [11, 22, 33, 44, 55]
])

arr1 = np.array([1, 2, 3, 4, 5])

print(arr + arr1)

[[11 22 33 44 55]
 [12 24 36 48 60]]
