In [2]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0])

[10 20 30]


In [3]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[2])

[70 80 90]


In [9]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0][0])
print(arr[1][0])
print(arr[2][0])

10
40
70


In [10]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0][2])
print(arr[1][2])
print(arr[2][2])

30
60
90


In [11]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1][1])

50


In [12]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0][2])
print(arr[2][0])
print(arr[2][2])

30
70
90


In [13]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1])

[40 50 60]


In [14]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0][1])
print(arr[1][1])
print(arr[2][1])

20
50
80


In [18]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0],arr[2])

[10 20 30] [70 80 90]


In [19]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0][0])
print(arr[1][0])
print(arr[2][0])
print(arr[0][2])
print(arr[1][2])
print(arr[2][2])

10
40
70
30
60
90


In [21]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[0,1] = 200
print(arr)

[[ 10 200  30]
 [ 40  50  60]
 [ 70  80  90]]


In [24]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr[1,1] = 100
arr[2,1] = 200
print(arr)

[[ 10  20  30]
 [ 40 100  60]
 [ 70 200  90]]


In [26]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(arr[0][0])
print(arr[0][3])
print(arr[1][2])
print(arr[2][1])

10
40
70
100


In [28]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[2][0])
print(arr[2][1])
print(arr[2][2])
print(arr[0][1])
print(arr[1][1])
print(arr[2][1])


70
80
90
20
50
80


In [29]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr[1])

[40 50 60]
