In [1]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.dtype)

int64


In [14]:
import numpy as np

arr = np.array([1.0,2.4,3.0,4.5])

print(arr.dtype)

float64


In [15]:
import numpy as np

arr = np.array([10, 20, 30])

print(type(arr))

<class 'numpy.ndarray'>


In [16]:
import numpy as np

salary = np.array([25000, 30000, 35000, 40000])

print(salary)

[25000 30000 35000 40000]


In [21]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr)
print(type(arr))
print(arr.dtype)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
int64


In [25]:
import numpy as np
arr = np.array([[80,70,60],[90,80,70]])
print(arr)

[[80 70 60]
 [90 80 70]]


In [3]:
import numpy as np
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr.ndim)

2


In [17]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.shape)

(5,)


In [19]:
import numpy as np

arr = np.array([10, 20, 30,40])

print(arr.size)

4


In [24]:
arr = np.array([[
    [10, 20, 30],
    [10, 20, 30],
    [2,4,6]
]])

print(arr.size)

9


In [29]:
import numpy as np
arr = np.array(["swamini","pooja"])
print(arr.dtype)

<U7


In [36]:
import numpy as np

arr = np.array([10, 20, 30, 40,50])

print(arr.itemsize)

8


In [35]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr.nbytes)

32


In [11]:
#methods astype()

import numpy as np
arr = np.array([10,20,30,40])
new_arr = arr.astype(float)
print(new_arr)
print(new_arr.dtype)

[10. 20. 30. 40.]
float64


In [27]:
import numpy as np

arr = np.array([10,20,30])

new_arr = arr.astype(float)

print(new_arr)
print(new_arr.dtype)

[10. 20. 30.]
float64


In [38]:
import numpy as np

arr = np.array([10, 20, 30])

new_arr = arr.copy()
arr[1] = 80
new_arr[0] = 100

print(arr)
print(new_arr)

[10 80 30]
[100  20  30]


In [35]:
import numpy as np
arr = np.array(["10",20,30.,40.])
new_arr = arr.copy()
print(arr)
print(new_arr)

['10' '20' '30.0' '40.0']
['10' '20' '30.0' '40.0']


In [40]:
import numpy as np
arr = np.array([10,20,30,40,50])
new_arr = arr.view()
new_arr[1] = 100
print(arr)
print(new_arr)

[ 10 100  30  40  50]
[ 10 100  30  40  50]


In [41]:
import numpy as np
arr = np.array([20,40,60,70])
new_arr = new_arr.copy()
new_arr[0] = 500
print(arr)
print(new_arr)

[20 40 60 70]
[500 100  30  40  50]


In [44]:
import numpy as np
arr = np.array([10,30,40,70,60])
new_arr = arr.view()
new_arr[0] = 500
print(arr)
print(new_arr)

[500  30  40  70  60]
[500  30  40  70  60]


In [45]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.tolist())

[10, 20, 30]


In [46]:
import numpy as np
arr = np.array([50,60,70,80])
print(arr.tolist())

[50, 60, 70, 80]


In [52]:
import numpy as np
arr = np.array([10,20,30,40,1,2])
print(arr.reshape(2,3))

[[10 20 30]
 [40  1  2]]


In [55]:
import numpy as np
arr = np.array([[10,20],[30,40]])
print(arr.flatten())

[10 20 30 40]


In [59]:
import numpy as np

arr = np.array([10, 20, 30])

arr.resize(3)

print(arr)

[10 20 30]


In [60]:
import numpy as np

arr = np.array([10, 20, 30])

new_arr = np.append(arr, 40)

print(new_arr)

[10 20 30 40]


In [5]:
import numpy as np

arr = np.array([10,30,50])
print(np.delete(arr,1))

[10 50]


In [8]:
import numpy as np

arr = np.array([65,87,32,80,70,])

print(np.delete(arr,3))

[65 87 32 70]


In [11]:
import numpy as np

arr = np.array([1,2,3,4])

arr2 = np.array([50,60,70])

print(np.concatenate((arr,arr2)))

[ 1  2  3  4 50 60 70]


In [15]:
import numpy as np

a = ([1,2,3,4,5,6,7,8,9,10])
b = ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

print(np.concatenate((a,b)))

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10 11 12 13 14
 15 16 17 18 19 20]


In [16]:
import numpy as np

arr = np.array([2,4])
arr2 = np.array([3,5])

print(np.stack((arr,arr2)))

[[2 4]
 [3 5]]


In [17]:
import numpy as np

arr = np.array([40,10,20,30])

print(np.sort(arr))

[10 20 30 40]


In [18]:
import numpy as np

arr = np.array([10, 0, 20, 0, 30])

print(np.nonzero(arr))

(array([0, 2, 4]),)


In [21]:
import numpy as np

arr = np.array([10,20,30,40])
print(np.searchsorted(arr,35))

3


In [22]:
import numpy as np

arr = np.array([10,20,20,30,30])

print(np.unique(arr))

[10 20 30]


In [23]:
import numpy as np

arr = np.array([10,0,20,0,30])

print(np.count_nonzero(arr))

3


In [27]:
import numpy as np

arr = np.array([1,1,1.0,0,20])

print(np.count_nonzero(arr))

4


In [31]:
import numpy as np

arr = np.array([10,20,30])

print(np.repeat(arr,2))

[10 10 20 20 30 30]


In [33]:
import numpy as np

arr = np.array([10,20,30,])

print(np.tile(arr,2))

[10 20 30 10 20 30]


In [34]:
import numpy as np
arr =np.array([10,20,30])
print(np.sum(arr))

60


In [37]:
import numpy as np

arr = np.array([1,2,3,4])

print(np.mean(arr))

2.5


In [41]:
import numpy as np

arr = np.array([85,90,75,88,92,10])

print(np.median(arr))

86.5


In [42]:
import numpy as np

arr = np.array([85,90,75,88,92])

print(np.max(arr))

92


In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.delete(arr,2))

[10 20 40 50]
