In [2]:
import numpy as np

A = np.array([11, 22, 33])
B = np.array([1, 2, 3])

print(A + B)


[12 24 36]


In [3]:
import numpy as np

A = np.array([11, 22, 33])
B = np.array([1, 2, 3])

print(A - B)


[10 20 30]


In [4]:
import numpy as np

A = np.array([11, 22, 33])
B = np.array([1, 2, 3])

print(A * B)


[11 44 99]


In [5]:
import numpy as np

A = np.array([11, 22, 33])
B = np.array([1, 2, 3])

print(A / B)


[11. 11. 11.]


In [6]:
import numpy as np

arr = np.array([2, 3, 4, 5])
print(np.square(arr))

[ 4  9 16 25]


In [8]:
import numpy as np 

arr = np.random.rand(5)
print(arr)

[0.82831147 0.85088575 0.20547851 0.67026151 0.18001084]


In [9]:
import numpy as np 

arr = np.random.randint(0,101,5)
print(arr)

[66 77 99 75 83]


In [11]:
import numpy as np 

arr = np.random.randint(0,101,(3,3))
print(arr)

[[45 45 46]
 [54 14 24]
 [55 43 58]]


In [13]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
print(A + B)

[[ 6  8]
 [10 12]]


In [14]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [17]:
import numpy as np

A = np.array([
    [4, 5],
    [6, 7]
])
det = np.linalg.det(A)
print(det)

-2.000000000000003


In [22]:
import numpy as np

A = np.array([
    [4, 5],
    [6, 7]
])
inv = np.linalg.inv(A)
print(inv)

[[-3.5  2.5]
 [ 3.  -2. ]]


In [30]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 1]
])
print(np.linalg.matrix_rank(A))

2


In [32]:
import numpy as np

A = np.array([
    [2, 0],
    [0, 5]
])

eigenvalues , eigenvectors = np.linalg.eig(A)
print(eigenvalues)

[2.+0.j 5.+0.j]


In [35]:
import numpy as np

A = np.array([
    [2,1],
    [1,3]
])

B = np.array([5,6])
print(np.linalg.solve(A,B))


[1.8 1.4]
