# 

In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [5]:
import numpy as np

arr = np.array([10,20,30,40])
print(arr.dtype)

int64


In [6]:
import numpy as np

arr = np.array([5,10,15,20,25])
print(np.size(arr))

5


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(np.ndim(arr))

1


In [9]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
print(arr[0])
print(arr[2])
print(arr[5])

10
30
60


In [10]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
print(arr[-1])
print(arr[-2])
print(arr[-3])

60
50
40


In [16]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


In [18]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70])
print(arr[2:6])

[30 40 50 60]


In [21]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr[[1,3]] = [100,200]
print(arr)


[ 10 100  30 200  50]


In [22]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [23]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1][1])
print(arr[2][2])

50
90


In [24]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0])


[10 20 30]


In [25]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[2])

[70 80 90]


In [26]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0][0])
print(arr[1][0])
print(arr[2][0])

10
40
70


In [27]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0][2])
print(arr[1][2])
print(arr[2][2])

30
60
90


In [28]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr.shape)

(3, 3)


In [29]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr[1][1] = 500
arr[2][2] = 900
print(arr)

[[ 10  20  30]
 [ 40 500  60]
 [ 70  80 900]]


In [31]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [32]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(np.mean(arr))

30.0


In [33]:
import numpy as np

arr = np.array([25, 10, 45, 30, 60])
print(np.max(arr))

60


In [34]:
import numpy as np

arr = np.array([25, 10, 45, 30, 60])
print(np.min(arr))

10


In [35]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(np.std(arr))

14.142135623730951


In [36]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(np.var(arr))

200.0


In [1]:
import numpy as np

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [2]:
import numpy as np

arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [4]:
import numpy as np

arr = np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [6]:
import numpy as np

arr = np.linspace(0,10,6)
print(arr)

[ 0.  2.  4.  6.  8. 10.]


In [8]:
import numpy as np

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np

arr = np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [16]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [18]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.flatten())

[1 2 3 4 5 6]


In [19]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [22]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(np.concatenate((A,B)))

[1 2 3 4 5 6]


In [25]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(np.vstack((A,B)))

[[1 2 3]
 [4 5 6]]


In [32]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.where(arr==30))

(array([2]),)


In [33]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.searchsorted(arr,35))

3


In [35]:
import numpy as np

arr = np.array([50, 20, 40, 10, 30])
print(np.sort(arr))

[10 20 30 40 50]


In [36]:
import numpy as np

arr = np.array([10, 20, 10, 30, 20, 40, 30])
print(np.unique(arr))


[10 20 30 40]


In [39]:
import numpy as np

arr = np.array([10, 25, 30, 15, 40])
print(np.where(arr>=20))

(array([1, 2, 4]),)
